//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Market {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Market.IPublicMarketService")]
    public interface IPublicMarketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicMarketService/Ping", ReplyAction="http://tempuri.org/IPublicMarketService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicMarketService/ActivateMeAt", ReplyAction="http://tempuri.org/IPublicMarketService/ActivateMeAtResponse")]
        void ActivateMeAt(string username, string password, string EndpointAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicMarketServiceChannel : Client.Market.IPublicMarketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicMarketServiceClient : System.ServiceModel.ClientBase<Client.Market.IPublicMarketService>, Client.Market.IPublicMarketService {
        
        public PublicMarketServiceClient() {
        }
        
        public PublicMarketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicMarketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicMarketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicMarketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public void ActivateMeAt(string username, string password, string EndpointAddress) {
            base.Channel.ActivateMeAt(username, password, EndpointAddress);
        }
    }
}
